OrdererOrgs:
  - Name: Orderer
    Domain: org0.unifit.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Org1
    Domain: org1.unifit.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.unifit.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
