version: '2.0'

networks:
  fabric-ca:
    name: fabric-ca

services:

  tlsca-org0:
    container_name: tlsca-org0
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b tlsca-org0-admin:tlsca-org0-AdminPW --port 11054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=tlsca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:metaust@tcp(47.98.184.198:3306)/fabric_tlsca_org0?parseTime=true
    volumes:
      - /tmp/hyperledger/org0/tlsca:/tmp/hyperledger/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 11051:11054

  ca-org0:
    container_name: ca-org0
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b ca-org0-admin:ca-org0-AdminPW --port 11054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:metaust@tcp(47.98.184.198:3306)/fabric_ca_org0?parseTime=true
    volumes:
      - /tmp/hyperledger/org0/ca:/tmp/hyperledger/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 11052:11054