version: '2.0'

networks:
  fabric-ca:
    name: fabric-ca

services:
  tlsca-org1:
    user: 1003:1004
    container_name: tlsca-org1
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b tlsca-org1-admin:tlsca-org1-AdminPW --port 7054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=tlsca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=false
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=fabric_ca_admin:fabric_ca2022@tcp(172.17.0.1:3306)/fabric_tlsca_org1?parseTime=true
    volumes:
      - ~/01_Fabric/hyperledger/org1/tlsca:/tmp/hyperledger/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7053:7054

  ca-org1:
    user: 1003:1004
    container_name: ca-org1
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b ca-org1-admin:ca-org1-AdminPW --port 7054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=false
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=fabric_ca_admin:fabric_ca2022@tcp(172.17.0.1:3306)/fabric_ca_org1?parseTime=true
    volumes:
      - ~/01_Fabric/hyperledger/org1/ca:/tmp/hyperledger/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 7054:7054
