version: '2.0'

networks:
  fabric-ca:
    name: fabric-ca

services:

  tlsca-org1:
    container_name: tlsca-org1
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b tlsca-org1-admin:tlsca-org1-AdminPW --port 11054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=tlsca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=false
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:metaust@tcp(47.98.184.198:3306)/fabric_tlsca_org1?parseTime=true
    volumes:
      - /tmp/hyperledger/org1/tlsca:/tmp/hyperledger/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 11053:11054

  ca-org1:
    container_name: ca-org1
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b ca-org1-admin:ca-org1-AdminPW --port 11054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=false
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:metaust@tcp(47.98.184.198:3306)/fabric_ca_org1?parseTime=true
    volumes:
      - /tmp/hyperledger/org1/ca:/tmp/hyperledger/fabric-ca
    networks:
      - fabric-ca
    ports:
      - 11054:11054
