version: '2.0'

networks:
  fabric-ca:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16

services:
  tlsca-org1:
    user: 1014:1014
    container_name: tlsca-org1
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b tlsca-org1-admin:tlsca-org1-AdminPW --port 7054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=tlsca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=false
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=fabric_ca_org_admin:fabric_ca_org2022@tcp(pascal.ieda.ust.hk:3306)/fabric_tlsca_org?parseTime=true
    volumes:
      - ~/01_Fabric/hyperledger/org1/tlsca:/tmp/hyperledger/fabric-ca
    networks:
      fabric-ca:
        ipv4_address: 172.18.0.13
    ports:
      - 7050:7054


  ca-org1:
    user: 1014:1014
    container_name: ca-org1
    image: hyperledger/fabric-ca:1.5.2
    command: /bin/sh -c 'fabric-ca-server start -d -b ca-org1-admin:ca-org1-AdminPW --port 7054'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=false
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=fabric_ca_org_admin:fabric_ca_org2022@tcp(pascal.ieda.ust.hk:3306)/fabric_ca_org?parseTime=true
    volumes:
      - ~/01_Fabric/hyperledger/org1/ca:/tmp/hyperledger/fabric-ca
    networks:
      fabric-ca:
        ipv4_address: 172.18.0.14
    ports:
      - 7051:7054