version: '2'

services:

  couchdb0.org1.unifit.com:
    # user: 1003:1004
    container_name: couchdb0.org1.unifit.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdb2022
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7084:5984"

  orderer1.org0.unifit.com:
    user: 1003:1004
    container_name: orderer1.org0.unifit.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7060
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ./orderer/var/hyperledger/:/var/hyperledger/
        # - ./orderer/var/hyperledger/orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        # - ./orderer/var/hyperledger/orderer/msp:/var/hyperledger/orderer/msp/
        # - ./orderer/var/hyperledger/orderer/tls:/var/hyperledger/orderer/tls/
        # - ./crypto-config/ordererOrganizations/org0.unifit.com/orderers/orderer1.org0.unifit.com/msp:/var/hyperledger/orderer/msp
        # - ./crypto-config/ordererOrganizations/org0.unifit.com/orderers/orderer1.org0.unifit.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7060:7060
    extra_hosts:
      - "orderer1.org0.unifit.com:172.17.0.1"
      - "orderer2.org0.unifit.com:172.17.0.1"

  peer0.org1.unifit.com:
    user: 1003:1004
    container_name: peer0.org1.unifit.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.unifit.com
      - CORE_PEER_ADDRESS=peer0.org1.unifit.com:7061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.unifit.com:7062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.unifit.com:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.unifit.com:7061
      - CORE_PEER_LOCALMSPID=Org1MSP
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Allow more time for chaincode container to build on install.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org1.unifit.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb2022
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./peer/etc/hyperledger/:/etc/hyperledger/
      - ./peer/var/hyperledger/:/var/hyperledger/
      - ./peer/etc/hyperledger/fabric/msp:/etc/hyperledger/fabric/msp/
      - ./peer/etc/hyperledger/fabric/tls:/etc/hyperledger/fabric/tls/
    ports:
      - 7061:7061
      - 7062:7062
      - 7063:7063
    extra_hosts:
      - "orderer1.org0.unifit.com:172.17.0.1"
      - "orderer2.org0.unifit.com:172.17.0.1"

  cli0.org1:
    container_name: cli0.org1
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli0.org1
      - CORE_PEER_ADDRESS=peer0.org1.unifit.com:7061
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.unifit.com/peers/peer0.org1.unifit.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.unifit.com/peers/peer0.org1.unifit.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.unifit.com/peers/peer0.org1.unifit.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.unifit.com/users/Admin.org1.unifit.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash 
    # -c 'adduser -u 1003 user -D; usermod -aG fabric root; su - user;'
    user: 1003:1004
    volumes:
      - ./cli:/opt/gopath/src/github.com/hyperledger/fabric/peer
      - /var/run/:/host/var/run/
      - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/multiple-deployment/chaincode/go
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/
      # - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./cli/crypto:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./cli/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
      - "orderer1.org0.unifit.com:172.17.0.1"
      - "orderer2.org0.unifit.com:172.17.0.1"
      - "peer0.org1.unifit.com:172.17.0.1"
      - "peer0.org2.unifit.com:172.17.0.1"

